export const outreachProspects = [
  {
    "id": "outreach-001",
    "type": "Outreach",
    "name": "Gatehouse School",
    "organisation": "Gatehouse School",
    "area": "West London",
    "location": "Hammersmith",
    "contactName": "",
    "contactEmail": "admissions@gatehouseschool.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-002",
    "type": "Outreach",
    "name": "Orchard House School",
    "organisation": "Orchard House School",
    "area": "West London",
    "location": "Chiswick",
    "contactName": "",
    "contactEmail": "admissions@orchardhs.org.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-003",
    "type": "Outreach",
    "name": "Clifton Lodge School",
    "organisation": "Clifton Lodge School",
    "area": "West London",
    "location": "Ealing",
    "contactName": "",
    "contactEmail": "admissions@cliftonlodgeschool.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-004",
    "type": "Outreach",
    "name": "Durston House",
    "organisation": "Durston House",
    "area": "West London",
    "location": "Ealing",
    "contactName": "",
    "contactEmail": "info@durstonhouse.org",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-005",
    "type": "Outreach",
    "name": "Bassett House School",
    "organisation": "Bassett House School",
    "area": "West London",
    "location": "Notting Hill",
    "contactName": "",
    "contactEmail": "admissions@bassetths.org.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-006",
    "type": "Outreach",
    "name": "Chepstow House School",
    "organisation": "Chepstow House School",
    "area": "West London",
    "location": "Notting Hill",
    "contactName": "",
    "contactEmail": "admissions@chepstowhouseschool.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-007",
    "type": "Outreach",
    "name": "Ashton House School",
    "organisation": "Ashton House School",
    "area": "West London",
    "location": "Isleworth",
    "contactName": "",
    "contactEmail": "admissions@ashtonhouse.com",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-008",
    "type": "Outreach",
    "name": "Tower House School",
    "organisation": "Tower House School",
    "area": "SW London",
    "location": "East Sheen",
    "contactName": "",
    "contactEmail": "admissions@thsboys.org.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-009",
    "type": "Outreach",
    "name": "St Philip’s School",
    "organisation": "St Philip’s School",
    "area": "SW London",
    "location": "Kensington",
    "contactName": "",
    "contactEmail": "office@stphilipsschool.co.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-010",
    "type": "Outreach",
    "name": "Broomwood Prep",
    "organisation": "Broomwood Prep",
    "area": "SW London",
    "location": "Clapham",
    "contactName": "",
    "contactEmail": "admissions@broomwood.com",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-011",
    "type": "Outreach",
    "name": "Newton Prep",
    "organisation": "Newton Prep",
    "area": "SW London",
    "location": "Battersea",
    "contactName": "",
    "contactEmail": "admissions@newtonprep.org",
    "contactType": "Admissions",
    "dateContacted": "2026-05-12",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "sent via contact form on website",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-012",
    "type": "Outreach",
    "name": "Falcons School",
    "organisation": "Falcons School",
    "area": "SW London",
    "location": "Putney",
    "contactName": "",
    "contactEmail": "office@falconsschool.co.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-013",
    "type": "Outreach",
    "name": "Prospect House School",
    "organisation": "Prospect House School",
    "area": "SW London",
    "location": "Putney",
    "contactName": "",
    "contactEmail": "info@prospecths.org.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-014",
    "type": "Outreach",
    "name": "The Roche School",
    "organisation": "The Roche School",
    "area": "SW London",
    "location": "Wandsworth",
    "contactName": "",
    "contactEmail": "office@therocheschool.com",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-015",
    "type": "Outreach",
    "name": "Westbridge Academy",
    "organisation": "Westbridge Academy",
    "area": "SW London",
    "location": "Clapham/Battersea",
    "contactName": "",
    "contactEmail": "info@westbridgeacademy.co.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-016",
    "type": "Outreach",
    "name": "Bishop Gilpin Primary School",
    "organisation": "Bishop Gilpin Primary School",
    "area": "Merton",
    "location": "Wimbledon",
    "contactName": "",
    "contactEmail": "info@bishopgilpin.org",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-017",
    "type": "Outreach",
    "name": "All Saints’ C of E Primary School",
    "organisation": "All Saints’ C of E Primary School",
    "area": "Merton",
    "location": "Wimbledon",
    "contactName": "",
    "contactEmail": "office@allsaints.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-018",
    "type": "Outreach",
    "name": "Aragon Primary School",
    "organisation": "Aragon Primary School",
    "area": "Merton",
    "location": "Morden",
    "contactName": "",
    "contactEmail": "reception@aragonprimary.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-019",
    "type": "Outreach",
    "name": "Beecholme Primary School",
    "organisation": "Beecholme Primary School",
    "area": "Merton",
    "location": "Mitcham",
    "contactName": "",
    "contactEmail": "school@beecholme.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-020",
    "type": "Outreach",
    "name": "Benedict Academy",
    "organisation": "Benedict Academy",
    "area": "Merton",
    "location": "Mitcham",
    "contactName": "",
    "contactEmail": "office@benedictacademy.org",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-021",
    "type": "Outreach",
    "name": "Bond Primary School",
    "organisation": "Bond Primary School",
    "area": "Merton",
    "location": "Mitcham",
    "contactName": "",
    "contactEmail": "bondprimary@bond.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-022",
    "type": "Outreach",
    "name": "Cranmer Primary School",
    "organisation": "Cranmer Primary School",
    "area": "Merton",
    "location": "Mitcham",
    "contactName": "",
    "contactEmail": "office@cranmer.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-023",
    "type": "Outreach",
    "name": "Dundonald Primary School",
    "organisation": "Dundonald Primary School",
    "area": "Merton",
    "location": "Wimbledon",
    "contactName": "",
    "contactEmail": "school@dundonald.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-024",
    "type": "Outreach",
    "name": "Garfield Primary School",
    "organisation": "Garfield Primary School",
    "area": "Merton",
    "location": "Wimbledon",
    "contactName": "",
    "contactEmail": "school@garfield.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-025",
    "type": "Outreach",
    "name": "Gorringe Park Primary School",
    "organisation": "Gorringe Park Primary School",
    "area": "Merton",
    "location": "Mitcham",
    "contactName": "",
    "contactEmail": "office@gorringepark.merton.gov.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-026",
    "type": "Outreach",
    "name": "Harris Primary Academy Merton",
    "organisation": "Harris Primary Academy Merton",
    "area": "Merton",
    "location": "Mitcham",
    "contactName": "",
    "contactEmail": "info@harrisprimarymerton.org.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-027",
    "type": "Outreach",
    "name": "Haslemere Primary School",
    "organisation": "Haslemere Primary School",
    "area": "Merton",
    "location": "Mitcham",
    "contactName": "",
    "contactEmail": "info@haslemere.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-028",
    "type": "Outreach",
    "name": "Hatfeild Primary School",
    "organisation": "Hatfeild Primary School",
    "area": "Merton",
    "location": "Morden",
    "contactName": "",
    "contactEmail": "school@hatfeild.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-029",
    "type": "Outreach",
    "name": "Hollymount Primary School",
    "organisation": "Hollymount Primary School",
    "area": "Merton",
    "location": "Wimbledon",
    "contactName": "",
    "contactEmail": "info@hollymount.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-030",
    "type": "Outreach",
    "name": "Holy Trinity C of E Primary School",
    "organisation": "Holy Trinity C of E Primary School",
    "area": "Merton",
    "location": "Wimbledon",
    "contactName": "",
    "contactEmail": "info@holytrinity.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-031",
    "type": "Outreach",
    "name": "Joseph Hood Primary School",
    "organisation": "Joseph Hood Primary School",
    "area": "Merton",
    "location": "Wimbledon",
    "contactName": "",
    "contactEmail": "josephhoodprimary@josephhood.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-032",
    "type": "Outreach",
    "name": "Liberty Primary School",
    "organisation": "Liberty Primary School",
    "area": "Merton",
    "location": "Morden",
    "contactName": "",
    "contactEmail": "liberty@liberty.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-033",
    "type": "Outreach",
    "name": "Links Primary School",
    "organisation": "Links Primary School",
    "area": "Merton",
    "location": "Mitcham",
    "contactName": "",
    "contactEmail": "office@links.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-034",
    "type": "Outreach",
    "name": "Lonesome Primary School",
    "organisation": "Lonesome Primary School",
    "area": "Merton",
    "location": "Mitcham",
    "contactName": "",
    "contactEmail": "lonesome@lonesome.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-035",
    "type": "Outreach",
    "name": "Malmesbury Primary School",
    "organisation": "Malmesbury Primary School",
    "area": "Merton",
    "location": "Morden",
    "contactName": "",
    "contactEmail": "school@malmesbury.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-036",
    "type": "Outreach",
    "name": "Merton Park Primary School",
    "organisation": "Merton Park Primary School",
    "area": "Merton",
    "location": "Wimbledon",
    "contactName": "",
    "contactEmail": "admin@mertonpark.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-037",
    "type": "Outreach",
    "name": "Morden Primary School",
    "organisation": "Morden Primary School",
    "area": "Merton",
    "location": "Morden",
    "contactName": "",
    "contactEmail": "info@morden.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-038",
    "type": "Outreach",
    "name": "Park Academy",
    "organisation": "Park Academy",
    "area": "Merton",
    "location": "Mitcham",
    "contactName": "",
    "contactEmail": "office@park-academy.org",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-039",
    "type": "Outreach",
    "name": "Pelham Primary School",
    "organisation": "Pelham Primary School",
    "area": "Merton",
    "location": "Wimbledon",
    "contactName": "",
    "contactEmail": "office@pelham.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-040",
    "type": "Outreach",
    "name": "Poplar Primary School",
    "organisation": "Poplar Primary School",
    "area": "Merton",
    "location": "Merton",
    "contactName": "",
    "contactEmail": "poplarprimaryschool@poplar.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-041",
    "type": "Outreach",
    "name": "Sacred Heart RC Primary School",
    "organisation": "Sacred Heart RC Primary School",
    "area": "Merton",
    "location": "Wimbledon",
    "contactName": "",
    "contactEmail": "school@sacredheart.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-042",
    "type": "Outreach",
    "name": "Singlegate Primary School",
    "organisation": "Singlegate Primary School",
    "area": "Merton",
    "location": "Mitcham",
    "contactName": "",
    "contactEmail": "school@singlegate.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-043",
    "type": "Outreach",
    "name": "St Peter & Paul RC Primary School",
    "organisation": "St Peter & Paul RC Primary School",
    "area": "Merton",
    "location": "Mitcham",
    "contactName": "",
    "contactEmail": "office@sspp.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-044",
    "type": "Outreach",
    "name": "St John Fisher RC Primary School",
    "organisation": "St John Fisher RC Primary School",
    "area": "Merton",
    "location": "Merton",
    "contactName": "",
    "contactEmail": "school@st-johnfisher.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-045",
    "type": "Outreach",
    "name": "St Mark’s Primary School",
    "organisation": "St Mark’s Primary School",
    "area": "Merton",
    "location": "Mitcham",
    "contactName": "",
    "contactEmail": "office@stmarks.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-046",
    "type": "Outreach",
    "name": "St Mary’s Primary School",
    "organisation": "St Mary’s Primary School",
    "area": "Merton",
    "location": "Wimbledon",
    "contactName": "",
    "contactEmail": "school@st-marys.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-047",
    "type": "Outreach",
    "name": "St Matthew’s C of E Primary School",
    "organisation": "St Matthew’s C of E Primary School",
    "area": "Merton",
    "location": "Merton",
    "contactName": "",
    "contactEmail": "office@st-matthews.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-048",
    "type": "Outreach",
    "name": "St Teresa’s RC Primary School",
    "organisation": "St Teresa’s RC Primary School",
    "area": "Merton",
    "location": "Morden",
    "contactName": "",
    "contactEmail": "school@st-teresas.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-049",
    "type": "Outreach",
    "name": "St Thomas of Canterbury Primary School",
    "organisation": "St Thomas of Canterbury Primary School",
    "area": "Merton",
    "location": "Mitcham",
    "contactName": "",
    "contactEmail": "office@st-thomascanterbury.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-050",
    "type": "Outreach",
    "name": "Stanford Primary School",
    "organisation": "Stanford Primary School",
    "area": "Merton",
    "location": "Norbury/Mitcham",
    "contactName": "",
    "contactEmail": "stanfordprimaryschool@stanford.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-051",
    "type": "Outreach",
    "name": "Sherwood Primary School",
    "organisation": "Sherwood Primary School",
    "area": "Merton",
    "location": "Mitcham",
    "contactName": "",
    "contactEmail": "adminoffice@sherwood.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-052",
    "type": "Outreach",
    "name": "The Priory CofE Primary School",
    "organisation": "The Priory CofE Primary School",
    "area": "Merton",
    "location": "Wimbledon",
    "contactName": "",
    "contactEmail": "school@thepriory.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-053",
    "type": "Outreach",
    "name": "West Wimbledon Primary School",
    "organisation": "West Wimbledon Primary School",
    "area": "Merton",
    "location": "Wimbledon",
    "contactName": "",
    "contactEmail": "school@westwimbledon.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-054",
    "type": "Outreach",
    "name": "William Morris Primary School",
    "organisation": "William Morris Primary School",
    "area": "Merton",
    "location": "Mitcham",
    "contactName": "",
    "contactEmail": "office@williammorris.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-055",
    "type": "Outreach",
    "name": "Wimbledon Park Primary School",
    "organisation": "Wimbledon Park Primary School",
    "area": "Merton",
    "location": "Wimbledon",
    "contactName": "",
    "contactEmail": "school@wimbledonpark.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-056",
    "type": "Outreach",
    "name": "Raynes Park Primary School",
    "organisation": "Raynes Park Primary School",
    "area": "Merton",
    "location": "Wimbledon",
    "contactName": "",
    "contactEmail": "school@raynespark.merton.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-057",
    "type": "Outreach",
    "name": "The Old Vicarage School",
    "organisation": "The Old Vicarage School",
    "area": "Richmond",
    "location": "Richmond",
    "contactName": "",
    "contactEmail": "admissions@tovs.org.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong prep",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong prep"
  },
  {
    "id": "outreach-058",
    "type": "Outreach",
    "name": "Marshgate Primary School",
    "organisation": "Marshgate Primary School",
    "area": "Richmond",
    "location": "Richmond",
    "contactName": "",
    "contactEmail": "info@marshgate.richmond.sch.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-059",
    "type": "Outreach",
    "name": "St Elizabeth’s Catholic Primary",
    "organisation": "St Elizabeth’s Catholic Primary",
    "area": "Richmond",
    "location": "Richmond",
    "contactName": "",
    "contactEmail": "office@stelizabeths.richmond.sch.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-060",
    "type": "Outreach",
    "name": "Darell Primary School",
    "organisation": "Darell Primary School",
    "area": "Richmond",
    "location": "Richmond",
    "contactName": "",
    "contactEmail": "info@darell.richmond.sch.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-061",
    "type": "Outreach",
    "name": "Holy Trinity CofE Primary",
    "organisation": "Holy Trinity CofE Primary",
    "area": "Richmond",
    "location": "Richmond",
    "contactName": "",
    "contactEmail": "office@holytrinity.richmond.sch.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-062",
    "type": "Outreach",
    "name": "The Russell Primary School",
    "organisation": "The Russell Primary School",
    "area": "Richmond",
    "location": "Richmond",
    "contactName": "",
    "contactEmail": "info@russell.richmond.sch.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-063",
    "type": "Outreach",
    "name": "St Richard’s CE Primary",
    "organisation": "St Richard’s CE Primary",
    "area": "Richmond",
    "location": "Richmond",
    "contactName": "",
    "contactEmail": "office@strichards.richmond.sch.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-064",
    "type": "Outreach",
    "name": "Radnor House Prep",
    "organisation": "Radnor House Prep",
    "area": "Twickenham",
    "location": "Twickenham",
    "contactName": "",
    "contactEmail": "admissions@radnorhouse.org",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-065",
    "type": "Outreach",
    "name": "Twickenham Primary Academy",
    "organisation": "Twickenham Primary Academy",
    "area": "Twickenham",
    "location": "Twickenham",
    "contactName": "",
    "contactEmail": "info@twickenhamprimaryacademy.org",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-066",
    "type": "Outreach",
    "name": "St Mary’s CE Primary",
    "organisation": "St Mary’s CE Primary",
    "area": "Twickenham",
    "location": "Twickenham",
    "contactName": "",
    "contactEmail": "admin@stmarys.richmond.sch.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-067",
    "type": "Outreach",
    "name": "Archdeacon Cambridge’s Primary",
    "organisation": "Archdeacon Cambridge’s Primary",
    "area": "Twickenham",
    "location": "Twickenham",
    "contactName": "",
    "contactEmail": "info@archdeaconcambridges.richmond.sch.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-068",
    "type": "Outreach",
    "name": "Trafalgar Infant School",
    "organisation": "Trafalgar Infant School",
    "area": "Twickenham",
    "location": "Twickenham",
    "contactName": "",
    "contactEmail": "info@trafalgar.richmond.sch.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-069",
    "type": "Outreach",
    "name": "St James’s Catholic Primary",
    "organisation": "St James’s Catholic Primary",
    "area": "Twickenham",
    "location": "Twickenham",
    "contactName": "",
    "contactEmail": "office@stjames.richmond.sch.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-070",
    "type": "Outreach",
    "name": "Hampton Prep School",
    "organisation": "Hampton Prep School",
    "area": "Hampton",
    "location": "Hampton",
    "contactName": "",
    "contactEmail": "admissions@hamptonprep.org.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Top target",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Top target"
  },
  {
    "id": "outreach-071",
    "type": "Outreach",
    "name": "Hampton Junior School",
    "organisation": "Hampton Junior School",
    "area": "Hampton",
    "location": "Hampton",
    "contactName": "",
    "contactEmail": "office@hamptonjunior.org.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-072",
    "type": "Outreach",
    "name": "Carlisle Infant School",
    "organisation": "Carlisle Infant School",
    "area": "Hampton",
    "location": "Hampton",
    "contactName": "",
    "contactEmail": "info@carlisle.richmond.sch.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-073",
    "type": "Outreach",
    "name": "Buckingham Primary School",
    "organisation": "Buckingham Primary School",
    "area": "Hampton",
    "location": "Hampton",
    "contactName": "",
    "contactEmail": "info@buckingham.richmond.sch.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-074",
    "type": "Outreach",
    "name": "St Mary’s CE Primary Hampton",
    "organisation": "St Mary’s CE Primary Hampton",
    "area": "Hampton",
    "location": "Hampton",
    "contactName": "",
    "contactEmail": "admin@stmarys-hampton.richmond.sch.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-075",
    "type": "Outreach",
    "name": "The Vineyard School",
    "organisation": "The Vineyard School",
    "area": "Richmond/Twickenham",
    "location": "Richmond",
    "contactName": "",
    "contactEmail": "office@vineyard.richmond.sch.uk",
    "contactType": "",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "SEN",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "SEN"
  },
  {
    "id": "outreach-076",
    "type": "Outreach",
    "name": "Fulham Prep School",
    "organisation": "Fulham Prep School",
    "area": "Fulham",
    "location": "Fulham",
    "contactName": "",
    "contactEmail": "admissions@fulhamprep.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Top target",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Top target"
  },
  {
    "id": "outreach-077",
    "type": "Outreach",
    "name": "Kensington Prep School (GDST)",
    "organisation": "Kensington Prep School (GDST)",
    "area": "Fulham",
    "location": "Fulham",
    "contactName": "",
    "contactEmail": "admissions@kps.gdst.net",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-078",
    "type": "Outreach",
    "name": "Parsons Green Prep School",
    "organisation": "Parsons Green Prep School",
    "area": "Fulham",
    "location": "Fulham",
    "contactName": "",
    "contactEmail": "admissions@parsonsgreenprep.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-079",
    "type": "Outreach",
    "name": "Lady Margaret School (Prep links)",
    "organisation": "Lady Margaret School (Prep links)",
    "area": "Fulham",
    "location": "Fulham",
    "contactName": "",
    "contactEmail": "info@lms.richmond.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Secondary feeder",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Secondary feeder"
  },
  {
    "id": "outreach-080",
    "type": "Outreach",
    "name": "St John’s Walham Green CE Primary",
    "organisation": "St John’s Walham Green CE Primary",
    "area": "Fulham",
    "location": "Fulham",
    "contactName": "",
    "contactEmail": "admin@stjohnsce.lbhf.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-081",
    "type": "Outreach",
    "name": "All Saints CE Primary Fulham",
    "organisation": "All Saints CE Primary Fulham",
    "area": "Fulham",
    "location": "Fulham",
    "contactName": "",
    "contactEmail": "admin@allsaintsfulham.lbhf.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-082",
    "type": "Outreach",
    "name": "Langford Primary School",
    "organisation": "Langford Primary School",
    "area": "Fulham",
    "location": "Fulham",
    "contactName": "",
    "contactEmail": "admin@langford.lbhf.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-083",
    "type": "Outreach",
    "name": "Sir John Lillie Primary School",
    "organisation": "Sir John Lillie Primary School",
    "area": "Fulham",
    "location": "Fulham",
    "contactName": "",
    "contactEmail": "admin@sirjohnlillie.lbhf.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-084",
    "type": "Outreach",
    "name": "Garden House School",
    "organisation": "Garden House School",
    "area": "Chelsea",
    "location": "Chelsea",
    "contactName": "",
    "contactEmail": "admissions@gardenhouseschool.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Top target",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Top target"
  },
  {
    "id": "outreach-085",
    "type": "Outreach",
    "name": "Sussex House School",
    "organisation": "Sussex House School",
    "area": "Chelsea",
    "location": "Chelsea",
    "contactName": "",
    "contactEmail": "registrar@sussexhouseschool.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-086",
    "type": "Outreach",
    "name": "Cameron Vale School",
    "organisation": "Cameron Vale School",
    "area": "Chelsea",
    "location": "Chelsea",
    "contactName": "",
    "contactEmail": "admissions@cameronvaleschool.com",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-087",
    "type": "Outreach",
    "name": "Marlborough Primary School",
    "organisation": "Marlborough Primary School",
    "area": "Chelsea",
    "location": "Chelsea",
    "contactName": "",
    "contactEmail": "admin@marlborough.rbkc.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-088",
    "type": "Outreach",
    "name": "Christ Church CE Primary Chelsea",
    "organisation": "Christ Church CE Primary Chelsea",
    "area": "Chelsea",
    "location": "Chelsea",
    "contactName": "",
    "contactEmail": "admin@christchurch.rbkc.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-089",
    "type": "Outreach",
    "name": "Holy Trinity CE Primary School",
    "organisation": "Holy Trinity CE Primary School",
    "area": "Chelsea",
    "location": "Chelsea",
    "contactName": "",
    "contactEmail": "admin@holytrinity.rbkc.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-090",
    "type": "Outreach",
    "name": "Thomas’s Kensington",
    "organisation": "Thomas’s Kensington",
    "area": "Kensington",
    "location": "Kensington",
    "contactName": "",
    "contactEmail": "admissions@thomas-s.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Top target",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Top target"
  },
  {
    "id": "outreach-091",
    "type": "Outreach",
    "name": "Thomas’s Battersea (for network)",
    "organisation": "Thomas’s Battersea (for network)",
    "area": "Kensington",
    "location": "Battersea",
    "contactName": "",
    "contactEmail": "admissions@thomas-s.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Network play",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Network play"
  },
  {
    "id": "outreach-092",
    "type": "Outreach",
    "name": "Wetherby School",
    "organisation": "Wetherby School",
    "area": "Kensington",
    "location": "Kensington",
    "contactName": "",
    "contactEmail": "admissions@wetherbyschool.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-093",
    "type": "Outreach",
    "name": "Pembridge Hall",
    "organisation": "Pembridge Hall",
    "area": "Kensington",
    "location": "Kensington",
    "contactName": "",
    "contactEmail": "admissions@pembridgehall.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-094",
    "type": "Outreach",
    "name": "Norland Place School",
    "organisation": "Norland Place School",
    "area": "Kensington",
    "location": "Kensington",
    "contactName": "",
    "contactEmail": "office@norlandplace.com",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-095",
    "type": "Outreach",
    "name": "St Mary Abbots CE Primary",
    "organisation": "St Mary Abbots CE Primary",
    "area": "Kensington",
    "location": "Kensington",
    "contactName": "",
    "contactEmail": "admin@st-maryabbots.rbkc.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-096",
    "type": "Outreach",
    "name": "Fox Primary School",
    "organisation": "Fox Primary School",
    "area": "Kensington",
    "location": "Kensington",
    "contactName": "",
    "contactEmail": "admin@fox.rbkc.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-097",
    "type": "Outreach",
    "name": "Bousfield Primary School",
    "organisation": "Bousfield Primary School",
    "area": "Kensington",
    "location": "Kensington",
    "contactName": "",
    "contactEmail": "admin@bousfield.rbkc.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-098",
    "type": "Outreach",
    "name": "Dulwich Prep & Senior",
    "organisation": "Dulwich Prep & Senior",
    "area": "Dulwich",
    "location": "Dulwich",
    "contactName": "",
    "contactEmail": "admissions@dulwichprep.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Top target",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Top target"
  },
  {
    "id": "outreach-099",
    "type": "Outreach",
    "name": "Alleyn’s Junior School",
    "organisation": "Alleyn’s Junior School",
    "area": "Dulwich",
    "location": "Dulwich",
    "contactName": "",
    "contactEmail": "admissions@alleyns.org.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-100",
    "type": "Outreach",
    "name": "James Allen’s Girls’ School (JAGS Junior)",
    "organisation": "James Allen’s Girls’ School (JAGS Junior)",
    "area": "Dulwich",
    "location": "Dulwich",
    "contactName": "",
    "contactEmail": "admissions@jags.org.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-101",
    "type": "Outreach",
    "name": "Oakfield Preparatory School",
    "organisation": "Oakfield Preparatory School",
    "area": "Dulwich",
    "location": "Dulwich",
    "contactName": "",
    "contactEmail": "office@oakfield.dulwich.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-102",
    "type": "Outreach",
    "name": "The Belham Primary School",
    "organisation": "The Belham Primary School",
    "area": "Dulwich",
    "location": "Peckham/Dulwich",
    "contactName": "",
    "contactEmail": "office@belham.southwark.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-103",
    "type": "Outreach",
    "name": "Dulwich Hamlet Junior School",
    "organisation": "Dulwich Hamlet Junior School",
    "area": "Dulwich",
    "location": "Dulwich",
    "contactName": "",
    "contactEmail": "office@dulwichhamletjuniorschool.org.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "new appointed wrap around care  - The Nook ",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-104",
    "type": "Outreach",
    "name": "Goose Green Primary School",
    "organisation": "Goose Green Primary School",
    "area": "Dulwich",
    "location": "East Dulwich",
    "contactName": "",
    "contactEmail": "office@goosegreen.southwark.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-105",
    "type": "Outreach",
    "name": "Harris Primary Academy Beckenham Green",
    "organisation": "Harris Primary Academy Beckenham Green",
    "area": "Beckenham",
    "location": "Beckenham",
    "contactName": "",
    "contactEmail": "info@harrisbeckenhamgreen.org.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-106",
    "type": "Outreach",
    "name": "Clare House Primary School",
    "organisation": "Clare House Primary School",
    "area": "Beckenham",
    "location": "Beckenham",
    "contactName": "",
    "contactEmail": "admin@clarehouse.bromley.sch.uk",
    "contactType": "Office",
    "dateContacted": "2026-05-12",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "Part of the Impact Multi Acadamy Trust",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-107",
    "type": "Outreach",
    "name": "Churchfields Primary School",
    "organisation": "Churchfields Primary School",
    "area": "Beckenham",
    "location": "Beckenham",
    "contactName": "",
    "contactEmail": "office@churchfields.bromley.sch.uk",
    "contactType": "Office",
    "dateContacted": "2026-05-12",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-108",
    "type": "Outreach",
    "name": "Marian Vian Primary School",
    "organisation": "Marian Vian Primary School",
    "area": "Beckenham",
    "location": "Beckenham",
    "contactName": "",
    "contactEmail": "marianvian@mslt.org.uk",
    "contactType": "Office",
    "dateContacted": "2026-05-12",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "Mosaic Schools Learning Trust",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-109",
    "type": "Outreach",
    "name": "St Mary’s Catholic Primary School",
    "organisation": "St Mary’s Catholic Primary School",
    "area": "Beckenham",
    "location": "Beckenham",
    "contactName": "",
    "contactEmail": "office@stmarys.beckenham.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-110",
    "type": "Outreach",
    "name": "Balgowan Primary School",
    "organisation": "Balgowan Primary School",
    "area": "Beckenham",
    "location": "Beckenham",
    "contactName": "",
    "contactEmail": "office@balgowan.bromley.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Existing link",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Existing link"
  },
  {
    "id": "outreach-111",
    "type": "Outreach",
    "name": "Pickhurst Academy",
    "organisation": "Pickhurst Academy",
    "area": "West Wickham",
    "location": "West Wickham",
    "contactName": "",
    "contactEmail": "office@pickhurst.bromley.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-112",
    "type": "Outreach",
    "name": "Hawes Down Primary School",
    "organisation": "Hawes Down Primary School",
    "area": "West Wickham",
    "location": "West Wickham",
    "contactName": "",
    "contactEmail": "office@hawesdown.bromley.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-113",
    "type": "Outreach",
    "name": "Oak Lodge Primary School",
    "organisation": "Oak Lodge Primary School",
    "area": "West Wickham",
    "location": "West Wickham",
    "contactName": "",
    "contactEmail": "office@oaklodge.bromley.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-114",
    "type": "Outreach",
    "name": "Wickham Common Primary School",
    "organisation": "Wickham Common Primary School",
    "area": "West Wickham",
    "location": "West Wickham",
    "contactName": "",
    "contactEmail": "office@wickhamcommon.bromley.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-115",
    "type": "Outreach",
    "name": "St David’s Prep",
    "organisation": "St David’s Prep",
    "area": "West Wickham",
    "location": "West Wickham",
    "contactName": "",
    "contactEmail": "office@stdavidsprep.com",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Very strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Very strong"
  },
  {
    "id": "outreach-116",
    "type": "Outreach",
    "name": "Unicorn Primary School",
    "organisation": "Unicorn Primary School",
    "area": "West Wickham",
    "location": "West Wickham",
    "contactName": "",
    "contactEmail": "office@unicorn.bromley.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-117",
    "type": "Outreach",
    "name": "Putney High School (Prep)",
    "organisation": "Putney High School (Prep)",
    "area": "Putney",
    "location": "Putney",
    "contactName": "",
    "contactEmail": "admissions@put.gdst.net",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-118",
    "type": "Outreach",
    "name": "Merlin School",
    "organisation": "Merlin School",
    "area": "Putney",
    "location": "Putney",
    "contactName": "",
    "contactEmail": "office@merlinschool.net",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-119",
    "type": "Outreach",
    "name": "Brandlehow Primary School",
    "organisation": "Brandlehow Primary School",
    "area": "Putney",
    "location": "Putney",
    "contactName": "",
    "contactEmail": "admin@brandlehow.wandsworth.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-120",
    "type": "Outreach",
    "name": "Hotham Primary School",
    "organisation": "Hotham Primary School",
    "area": "Putney",
    "location": "Putney",
    "contactName": "",
    "contactEmail": "admin@hotham.wandsworth.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-121",
    "type": "Outreach",
    "name": "St Mary’s CE Primary Putney",
    "organisation": "St Mary’s CE Primary Putney",
    "area": "Putney",
    "location": "Putney",
    "contactName": "",
    "contactEmail": "admin@stmarysschoolputney.co.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-122",
    "type": "Outreach",
    "name": "All Saints’ CE Primary Putney",
    "organisation": "All Saints’ CE Primary Putney",
    "area": "Putney",
    "location": "Putney",
    "contactName": "",
    "contactEmail": "admin@allsaints.wandsworth.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-123",
    "type": "Outreach",
    "name": "Emanuel School (Junior links)",
    "organisation": "Emanuel School (Junior links)",
    "area": "Wandsworth",
    "location": "Wandsworth",
    "contactName": "",
    "contactEmail": "admissions@emanuel.org.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Secondary link",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Secondary link"
  },
  {
    "id": "outreach-124",
    "type": "Outreach",
    "name": "Wandsworth Prep School",
    "organisation": "Wandsworth Prep School",
    "area": "Wandsworth",
    "location": "Wandsworth",
    "contactName": "",
    "contactEmail": "admissions@wandsworthprep.com",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Top target",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Top target"
  },
  {
    "id": "outreach-125",
    "type": "Outreach",
    "name": "St Anne’s CE Primary School",
    "organisation": "St Anne’s CE Primary School",
    "area": "Wandsworth",
    "location": "Wandsworth",
    "contactName": "",
    "contactEmail": "admin@stannes.wandsworth.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-126",
    "type": "Outreach",
    "name": "Swaffield Primary School",
    "organisation": "Swaffield Primary School",
    "area": "Wandsworth",
    "location": "Wandsworth",
    "contactName": "",
    "contactEmail": "admin@swaffield.wandsworth.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-127",
    "type": "Outreach",
    "name": "Beatrix Potter Primary School",
    "organisation": "Beatrix Potter Primary School",
    "area": "Wandsworth",
    "location": "Wandsworth",
    "contactName": "",
    "contactEmail": "admin@beatrixpotter.wandsworth.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-128",
    "type": "Outreach",
    "name": "Riversdale Primary School",
    "organisation": "Riversdale Primary School",
    "area": "Wandsworth",
    "location": "Wandsworth",
    "contactName": "",
    "contactEmail": "admin@riversdale.wandsworth.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-129",
    "type": "Outreach",
    "name": "West Hill Primary School",
    "organisation": "West Hill Primary School",
    "area": "Wandsworth",
    "location": "Wandsworth",
    "contactName": "",
    "contactEmail": "admin@westhill.wandsworth.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-130",
    "type": "Outreach",
    "name": "Sheringdale Primary School",
    "organisation": "Sheringdale Primary School",
    "area": "Wandsworth",
    "location": "Wandsworth",
    "contactName": "",
    "contactEmail": "admin@sheringdale.wandsworth.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-131",
    "type": "Outreach",
    "name": "Honeywell Infant & Junior Schools",
    "organisation": "Honeywell Infant & Junior Schools",
    "area": "Wandsworth",
    "location": "Wandsworth",
    "contactName": "",
    "contactEmail": "admin@honeywell.wandsworth.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-132",
    "type": "Outreach",
    "name": "Belleville Primary School",
    "organisation": "Belleville Primary School",
    "area": "Wandsworth",
    "location": "Wandsworth",
    "contactName": "",
    "contactEmail": "admin@belleville.wandsworth.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-133",
    "type": "Outreach",
    "name": "Alderbrook Primary School",
    "organisation": "Alderbrook Primary School",
    "area": "Wandsworth",
    "location": "Wandsworth",
    "contactName": "",
    "contactEmail": "admin@alderbrook.wandsworth.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-134",
    "type": "Outreach",
    "name": "Farringtons School (Prep)",
    "organisation": "Farringtons School (Prep)",
    "area": "Chislehurst",
    "location": "Chislehurst",
    "contactName": "",
    "contactEmail": "admissions@farringtons.org.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Top target",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Top target"
  },
  {
    "id": "outreach-135",
    "type": "Outreach",
    "name": "Babington House School",
    "organisation": "Babington House School",
    "area": "Chislehurst",
    "location": "Chislehurst",
    "contactName": "",
    "contactEmail": "admissions@babingtonhouse.com",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-136",
    "type": "Outreach",
    "name": "Mead Road Infant School",
    "organisation": "Mead Road Infant School",
    "area": "Chislehurst",
    "location": "Chislehurst",
    "contactName": "",
    "contactEmail": "office@meadroad.bromley.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-137",
    "type": "Outreach",
    "name": "Red Hill Primary School",
    "organisation": "Red Hill Primary School",
    "area": "Chislehurst",
    "location": "Chislehurst",
    "contactName": "",
    "contactEmail": "office@redhill.bromley.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-138",
    "type": "Outreach",
    "name": "St Nicholas CE Primary School",
    "organisation": "St Nicholas CE Primary School",
    "area": "Chislehurst",
    "location": "Chislehurst",
    "contactName": "",
    "contactEmail": "office@stnicholas.bromley.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-139",
    "type": "Outreach",
    "name": "Edgebury Primary School",
    "organisation": "Edgebury Primary School",
    "area": "Chislehurst",
    "location": "Chislehurst",
    "contactName": "",
    "contactEmail": "office@edgebury.bromley.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-140",
    "type": "Outreach",
    "name": "Sevenoaks Prep School",
    "organisation": "Sevenoaks Prep School",
    "area": "Sevenoaks",
    "location": "Sevenoaks",
    "contactName": "",
    "contactEmail": "admissions@sevenoaksprep.com",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Top target",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Top target"
  },
  {
    "id": "outreach-141",
    "type": "Outreach",
    "name": "Walthamstow Hall Junior School",
    "organisation": "Walthamstow Hall Junior School",
    "area": "Sevenoaks",
    "location": "Sevenoaks",
    "contactName": "",
    "contactEmail": "admissions@whall.school",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-142",
    "type": "Outreach",
    "name": "Russell House School",
    "organisation": "Russell House School",
    "area": "Sevenoaks",
    "location": "Sevenoaks",
    "contactName": "",
    "contactEmail": "office@russellhouseschool.co.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-143",
    "type": "Outreach",
    "name": "St Michael’s Prep School",
    "organisation": "St Michael’s Prep School",
    "area": "Sevenoaks",
    "location": "Otford (Sevenoaks)",
    "contactName": "",
    "contactEmail": "admissions@stmichaelsprep.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Top target",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Top target"
  },
  {
    "id": "outreach-144",
    "type": "Outreach",
    "name": "Riverhead Infants School",
    "organisation": "Riverhead Infants School",
    "area": "Sevenoaks",
    "location": "Sevenoaks",
    "contactName": "",
    "contactEmail": "office@riverhead.kent.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-145",
    "type": "Outreach",
    "name": "Amherst School",
    "organisation": "Amherst School",
    "area": "Sevenoaks",
    "location": "Sevenoaks",
    "contactName": "",
    "contactEmail": "office@amherst.kent.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-146",
    "type": "Outreach",
    "name": "Lady Boswell’s CE Primary School",
    "organisation": "Lady Boswell’s CE Primary School",
    "area": "Sevenoaks",
    "location": "Sevenoaks",
    "contactName": "",
    "contactEmail": "office@ladyboswells.kent.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-147",
    "type": "Outreach",
    "name": "Caterham Prep School",
    "organisation": "Caterham Prep School",
    "area": "Caterham",
    "location": "Caterham",
    "contactName": "",
    "contactEmail": "admissions@caterhamprep.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Top target",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Top target"
  },
  {
    "id": "outreach-148",
    "type": "Outreach",
    "name": "Oakhyrst Grange School",
    "organisation": "Oakhyrst Grange School",
    "area": "Caterham",
    "location": "Caterham",
    "contactName": "",
    "contactEmail": "admissions@oakhyrstgrange.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-149",
    "type": "Outreach",
    "name": "Cumnor House School (Boys)",
    "organisation": "Cumnor House School (Boys)",
    "area": "Caterham",
    "location": "Caterham",
    "contactName": "",
    "contactEmail": "admissions@cumnor.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-150",
    "type": "Outreach",
    "name": "Cumnor House School (Girls)",
    "organisation": "Cumnor House School (Girls)",
    "area": "Caterham",
    "location": "Caterham",
    "contactName": "",
    "contactEmail": "admissions@cumnorgirls.co.uk",
    "contactType": "Admissions",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "⭐ Strong",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "⭐ Strong"
  },
  {
    "id": "outreach-151",
    "type": "Outreach",
    "name": "Hillcroft Primary School",
    "organisation": "Hillcroft Primary School",
    "area": "Caterham",
    "location": "Caterham",
    "contactName": "",
    "contactEmail": "office@hillcroft.croydon.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-152",
    "type": "Outreach",
    "name": "Audley Primary School",
    "organisation": "Audley Primary School",
    "area": "Caterham",
    "location": "Caterham",
    "contactName": "",
    "contactEmail": "office@audley.croydon.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  },
  {
    "id": "outreach-153",
    "type": "Outreach",
    "name": "St John’s CE Primary School",
    "organisation": "St John’s CE Primary School",
    "area": "Caterham",
    "location": "Caterham",
    "contactName": "",
    "contactEmail": "office@stjohns.caterham.sch.uk",
    "contactType": "Office",
    "dateContacted": "",
    "followUpDate": "",
    "responseReceived": "",
    "status": "Prospect",
    "note": "",
    "subject": "School outreach prospect",
    "nextAction": "Manual outreach / follow-up",
    "stage": "Prospect"
  }
];
